name: check_scripts

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: pytorch/pytorch
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install system packets
      run: |
        sudo apt update
        sudo apt install --yes flake8 mypy pylint3 shellcheck libpython3.7-dev python3-numpy
    - name: install pip packets
      run: pip install onnx
    - name: run_checks
      run: |
        export PYTHONPATH="/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages:$(pwd)/code/python_tools"
        code/snippets/check_scripts.sh .
