name: check_scripts

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghdl/vunit:gcc-master
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install system packets
      run: sudo apt-get install flake8 mypy pylint3 shellcheck
    - name: install pip packets
      run: pip install onnx
    - name: run_checks
      run: code/snippets/check_scripts.sh .
