name: synthesis

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: ghdl/synth:beta
    steps:
      - uses: actions/checkout@v1
      - name: install pip and pip packets
        run: |
          apt update
          apt install --yes python3-pip
          pip3 install onnx
      - name: Run synthesis
        continue-on-error: true
        run: |
          export PYTHONPATH="$(pwd)/code/python_tools"
          code/snippets/synthesize.sh .
